name:  Docker-Multi-Arch
  
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:
     inputs:
      tagName:
        description: 'Tag Name'     
        required: true
        default: 'latest'
        
# Add permissions for GITHUB_TOKEN to push to GHCR
permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build for arm64
    strategy:
      matrix:
        max_cpus: [2, 4, 8]
    steps:
    - uses: actions/checkout@v5
      with:
          submodules: recursive

    - name: Extract tag name
      id: extract_tag
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
        elif [[ "${{ github.event.inputs.tagName }}" != "" ]]; then
          echo "tag_name=${{ github.event.inputs.tagName }}" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
        else
          echo "is_tag=false" >> $GITHUB_OUTPUT
        fi

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    # Setup hardware emulator using QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
        
    # Setup Docker Buildx for multi-arch images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract Docker metadata for latest
      id: meta-latest
      if: steps.extract_tag.outputs.is_tag == 'false'
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/ilmax/loxilb
        tags: |
          type=raw,value=latest-cpu${{ matrix.max_cpus }}
        labels: |
          org.opencontainers.image.title=loxilb-arm-fix
          org.opencontainers.image.description=Patched loxilb eBPF objects for ARM devices with MAX_REAL_CPUS=${{ matrix.max_cpus }}
          org.opencontainers.image.vendor=ilmax
          org.opencontainers.image.licenses=MIT
          max_real_cpus=${{ matrix.max_cpus }}

    - name: Extract Docker metadata for tag
      id: meta-tag
      if: steps.extract_tag.outputs.is_tag == 'true'
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/ilmax/loxilb
        tags: |
          type=raw,value=${{ steps.extract_tag.outputs.tag_name }}-cpu${{ matrix.max_cpus }}
        labels: |
          org.opencontainers.image.title=loxilb-arm-fix
          org.opencontainers.image.description=Patched loxilb eBPF objects for ARM devices with MAX_REAL_CPUS=${{ matrix.max_cpus }}
          org.opencontainers.image.vendor=ilmax
          org.opencontainers.image.licenses=MIT
          max_real_cpus=${{ matrix.max_cpus }}
          upstream_version=${{ steps.extract_tag.outputs.tag_name }}
      
    - name: Build Check
      if: |
          github.repository != 'ilmax/loxilb-arm-fix'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: false
        build-args: MAX_REAL_CPUS=${{ matrix.max_cpus }}
        tags: ghcr.io/ilmax/loxilb:latest-cpu${{ matrix.max_cpus }}
          
    - name: Build and push to latest
      id: build-latest
      if: |
          github.repository == 'ilmax/loxilb-arm-fix' 
          && steps.extract_tag.outputs.is_tag == 'false'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: true
        build-args: MAX_REAL_CPUS=${{ matrix.max_cpus }}
        tags: ${{ steps.meta-latest.outputs.tags }}
        labels: ${{ steps.meta-latest.outputs.labels }}

    - name: Generate artifact attestation for latest
      if: |
          github.repository == 'ilmax/loxilb-arm-fix' 
          && steps.extract_tag.outputs.is_tag == 'false'
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/ilmax/loxilb
        subject-digest: ${{ steps.build-latest.outputs.digest }}
        push-to-registry: true

    - name: Build and push to given tag
      id: build-tag
      if: |
          github.repository == 'ilmax/loxilb-arm-fix' 
          && steps.extract_tag.outputs.is_tag == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: true
        build-args: |
          TAG=${{ steps.extract_tag.outputs.tag_name }}
          MAX_REAL_CPUS=${{ matrix.max_cpus }}
        tags: ${{ steps.meta-tag.outputs.tags }}
        labels: ${{ steps.meta-tag.outputs.labels }}

    - name: Generate artifact attestation for tag
      if: |
          github.repository == 'ilmax/loxilb-arm-fix' 
          && steps.extract_tag.outputs.is_tag == 'true'
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/ilmax/loxilb
        subject-digest: ${{ steps.build-tag.outputs.digest }}
        push-to-registry: true
    